/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_simjessimsol_simcv_NativeDetection */

#ifndef _Included_com_simjessimsol_simcv_NativeDetection
#define _Included_com_simjessimsol_simcv_NativeDetection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_simjessimsol_simcv_NativeDetection
 * Method:    sendCascadeFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_simjessimsol_simcv_NativeDetection_sendCascadeFile
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_simjessimsol_simcv_NativeDetection
 * Method:    nativeDetectFace
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_simjessimsol_simcv_NativeDetection_nativeDetectFace
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
